#!/bin/bash
#
META="http://169.254.169.254/latest"
_die() { echo >&2 "$@"; exit 1; }
_usage() { _die "usage: $0"; }
_meta() {
  curl -sf --connect-timeout 3 "$META/meta-data/$1" -H "X-aws-ec2-metadata-token: $METATOKEN" || \
  _die "Failed to fetch EC2 metadata $1";
}
_procs() { { pidof "$@" || :; } | wc -w; }

METATOKEN=$(curl -s -X PUT "$META/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 60")
[[ -n "$METATOKEN" ]] || _die "Can't access instance meta-data."

INSTANCEID=$(_meta instance-id)
AZ=$(_meta placement/availability-zone)
export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-${AZ%[a-z]}}
export PATH="$PATH:/snap/bin"

PROCNAME="${1:-/usr/sbin/nagios}"
VALUE=$(_procs $PROCNAME)

if aws cloudwatch put-metric-data \
     --namespace Nagios \
     --metric-name $(basename "$PROCNAME") \
     --unit Count \
     --value "$VALUE" \
     --dimensions "InstanceId=${INSTANCEID}"
then
  [[ $VALUE = 0 ]] && STATUS=WARNING || STATUS=OK
  echo "CloudWatch $STATUS: $VALUE process(s) of $PROCNAME are running."
  [[ $VALUE = 0 ]] && exit 1
  exit 0
else
  echo "CloudWatch CRITICAL: aws command failed status=$?"
  exit 2
fi
